"""Identity_Service — UUIDv7 generation, canonical-form validation, and
Identifier_Registry persistence with audit-aware conflict rejection.

Design references:

- ``.kiro/specs/first-walking-slice/design.md`` §"Identity_Service" — the
  public surface implemented here (every ``new_*`` factory plus
  :meth:`IdentityService.validate_canonical` and
  :meth:`IdentityService.reject_if_duplicate`).
- AD-WS-2 — every managed identity is a UUIDv7 in canonical lowercase
  hyphenated 8-4-4-4-12 hex form, generated by ``Identity_Service``.
- AD-WS-3 — Resource Identity and Resource Revision Identity (and Trail
  Identity vs Trail Revision Identity) are independent values. The
  separate factory methods exposed here let callers obtain each kind of
  identifier without leaking that they all share the UUIDv7 generator.
- AD-WS-5 — when a caller passes a SQLAlchemy connection to
  :meth:`IdentityService.reject_if_duplicate`, the binding row is
  inserted into ``Identifier_Registry`` *inside the caller's transaction*
  so identifier persistence is atomic with the originating write.
- Design §"Error Handling — Identifier conflict (Requirement 1.4)":
  on a conflict :meth:`reject_if_duplicate` appends a Denial Record
  carrying ``reason_code='identifier-conflict'`` in a separate audit-only
  transaction, then raises :class:`IdentityConflictError` so the
  caller's originating transaction rolls back.

Task scope (task 2.2):

This module adds *persistent* registry behavior on top of task 2.1's
in-memory surface. Behaviour is selected by whether the caller passes a
SQLAlchemy connection to :meth:`reject_if_duplicate`:

- No connection — the in-memory ``dict``-backed registry from task 2.1
  is used. This is what unit tests that construct ``IdentityService()``
  with no arguments rely on.
- Connection supplied — the SQL ``Identifier_Registry`` table is the
  source of truth and a row is INSERTed inside the caller's transaction.
  On conflict, the service uses its injected engine + audit log to
  append a Denial Record from a separate transaction.

Requirements satisfied:

- 1.1 — every managed entity receives exactly one UUIDv7 in canonical
        lowercase 8-4-4-4-12 hex form before becoming referenceable
        (factories are unchanged from task 2.1).
- 1.2 — Resource vs Revision (and Trail vs Trail Revision) identities
        are produced by separate factory methods.
- 1.4 — re-binding an identifier to different domain content is rejected
        with :class:`IdentityConflictError`; a Denial Record is appended
        per design §"Error Handling" before the exception propagates.
- 1.6 — once issued and persisted, an identifier row in
        ``Identifier_Registry`` is never re-bound to a different
        content digest. UPDATE/DELETE on the table are rejected by the
        triggers installed in :mod:`walking_slice.persistence`.
- 1.7 — no business meaning is embedded; identifiers come from
        ``uuid_utils.uuid7()`` and the ``kind``/``content_digest``
        columns are written exactly as the caller supplies them.
"""

from __future__ import annotations

import re
import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Final, NewType, Optional

import uuid_utils
from sqlalchemy import text
from sqlalchemy.engine import Connection, Engine
from sqlalchemy.exc import SQLAlchemyError

from walking_slice.audit import AuditAppendError, AuditLog, format_iso8601_ms
from walking_slice.clock import Clock


__all__ = [
    "ALLOWED_IDENTIFIER_KINDS",
    "CANONICAL_UUID7_REGEX",
    "IDENTIFIER_CONFLICT_REASON_CODE",
    "IdentityConflictError",
    "IdentityFormatError",
    "IdentityService",
    "ImmutableRecordId",
    "ManifestId",
    "RegionId",
    "RelationshipId",
    "ResourceId",
    "RevisionId",
    "TrailId",
    "TrailRevisionId",
    "TrailStepId",
]


# ---------------------------------------------------------------------------
# Canonical-form regex.
#
# Per design §"Cross-Cutting Concerns" (*Identifier generation*) and AD-WS-2.
# - ``[0-9a-f]`` excludes uppercase to enforce the lowercase canonical form.
# - The third group starts with ``7`` (UUID version nibble).
# - The fourth group starts with one of ``[89ab]`` (variant bits 10xx).
# ---------------------------------------------------------------------------


CANONICAL_UUID7_REGEX: Final[re.Pattern[str]] = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)


# ---------------------------------------------------------------------------
# Identifier kinds accepted by the ``Identifier_Registry.kind`` CHECK
# constraint (see :mod:`walking_slice.persistence`). Centralized here so the
# Python surface fails fast on a typo before reaching the database, and so
# downstream callers can pick from a single authoritative set.
# ---------------------------------------------------------------------------


ALLOWED_IDENTIFIER_KINDS: Final[frozenset[str]] = frozenset(
    {
        "resource",
        "revision",
        "relationship",
        "region",
        "region_occurrence",
        "immutable_record",
        "trail",
        "trail_revision",
        "trail_step",
        "manifest",
    }
)


# ---------------------------------------------------------------------------
# Reason code written to ``Audit_Records.reason_code`` for every denial
# appended by :meth:`IdentityService.reject_if_duplicate`. Pinned by the
# Identifier-conflict path in design §"Error Handling".
# ---------------------------------------------------------------------------


IDENTIFIER_CONFLICT_REASON_CODE: Final[str] = "identifier-conflict"


# ---------------------------------------------------------------------------
# Distinct identifier types.
#
# These are ``NewType`` aliases over :class:`str` so they round-trip through
# JSON/SQL without conversion but remain statically distinguishable from a
# bare ``str``. Pydantic value objects in :mod:`walking_slice.models` accept
# them transparently when coerced to :class:`uuid.UUID`.
# ---------------------------------------------------------------------------


ResourceId = NewType("ResourceId", str)
RevisionId = NewType("RevisionId", str)
RelationshipId = NewType("RelationshipId", str)
RegionId = NewType("RegionId", str)
ImmutableRecordId = NewType("ImmutableRecordId", str)
TrailId = NewType("TrailId", str)
TrailRevisionId = NewType("TrailRevisionId", str)
TrailStepId = NewType("TrailStepId", str)
ManifestId = NewType("ManifestId", str)


# ---------------------------------------------------------------------------
# Errors raised by the service.
# ---------------------------------------------------------------------------


class IdentityFormatError(ValueError):
    """Raised when an identifier is not in canonical UUIDv7 form.

    Maps to the malformed-identifier branch of Requirement 1.4 ("…or
    would introduce a malformed identifier…"). It is a subclass of
    :class:`ValueError` so callers that already catch validation
    failures continue to work; downstream code may also catch this type
    specifically when it needs to distinguish format errors from
    conflicts.
    """


class IdentityConflictError(Exception):
    """Raised by :meth:`IdentityService.reject_if_duplicate` when an
    existing identifier is being rebound to a different content digest.

    Maps to the duplicate-content branch of Requirement 1.4 ("…would
    assign an existing identifier to different domain content…"). On the
    persistent path the service appends a Denial Record (reason_code
    ``'identifier-conflict'``) to ``Audit_Records`` in a separate
    transaction before raising this exception, so that the caller's
    originating transaction rolls back without losing the audit trail
    of the attempt — see design §"Error Handling".
    """

    def __init__(
        self,
        identifier: str,
        existing_digest: str,
        attempted_digest: str,
    ) -> None:
        super().__init__(
            f"identifier {identifier!r} is already bound to content digest "
            f"{existing_digest!r}; refusing to rebind to {attempted_digest!r}."
        )
        self.identifier = identifier
        self.existing_digest = existing_digest
        self.attempted_digest = attempted_digest


# ---------------------------------------------------------------------------
# IdentityService.
# ---------------------------------------------------------------------------


# Sentinel used internally to distinguish "the identifier has been issued
# but has not yet been bound to a content digest" from "bound to the empty
# string". The empty string is a legitimate digest input — callers may pass
# it for entities that have no content (Region, Manifest, etc.) — so we
# cannot use ``""`` as the sentinel. ``object()`` would defeat hashing
# semantics; ``None`` is reserved as the "not present" return from ``dict.get``.
_UNBOUND: Final[str] = "\x00unbound\x00"


@dataclass
class IdentityService:
    """Generate, validate, and bind identifiers for the slice.

    The service supports two operating modes:

    1. **In-memory mode** — constructed as ``IdentityService()`` with no
       arguments. A process-local ``dict`` tracks issued identifiers and
       their bindings. Used by task 2.1's unit tests and by any caller
       that does not yet need durable persistence.
    2. **Persistent mode** — constructed with ``engine`` (the slice's
       SQLAlchemy engine) and ``audit_log`` (so denial records on
       identifier conflict can be written from a separate transaction).
       In this mode callers pass a ``connection`` to
       :meth:`reject_if_duplicate` and the binding row is INSERTed into
       ``Identifier_Registry`` inside the caller's transaction per
       AD-WS-5. The injected ``clock`` supplies ``issued_at`` timestamps
       when the caller does not provide one explicitly.

    Both modes coexist on a single instance: a service constructed with
    an engine can still be called without a connection and will fall
    through to the in-memory path. This keeps the existing task-2.1
    behaviour available for callers that have not yet been wired to the
    transactional surface (and lets tests target either path directly).

    Thread-safety:
        Instances are safe to call from multiple threads — every mutation
        of the in-memory registry is guarded by an internal lock. The
        SQL path relies on SQLite's writer serialization plus the
        ``UNIQUE(identifier)`` constraint on ``Identifier_Registry`` to
        guarantee non-reuse.
    """

    engine: Optional[Engine] = None
    audit_log: Optional[AuditLog] = None
    clock: Optional[Clock] = None

    # ``field(default_factory=...)`` keeps each instance's registry independent;
    # this is critical because tests construct a fresh service per case and
    # property test 10 ("identity opacity and uniqueness") requires uniqueness
    # within a session but explicitly not across processes.
    _registry: dict[str, str] = field(default_factory=dict)
    _lock: threading.Lock = field(default_factory=threading.Lock)

    # -- generation factories -------------------------------------------------
    #
    # Each ``new_*`` method is a separate entry point so that callers (and
    # readers of the call graph) can see exactly which kind of identifier
    # is being minted. The implementations all funnel through
    # ``_new_canonical_uuid7`` because AD-WS-2 says every managed identity
    # uses the same generator; having distinct surface methods keeps the
    # design-level separation visible.
    #
    # The factories deliberately do NOT persist a row in
    # ``Identifier_Registry`` themselves. Per AD-WS-5 the registry row must
    # land in the same transaction as the originating write — the caller
    # therefore invokes :meth:`reject_if_duplicate` (with their connection)
    # at the moment they have computed the entity's content digest.

    def new_resource_id(self) -> ResourceId:
        """Return a fresh UUIDv7 to identify a managed Resource."""
        return ResourceId(self._new_canonical_uuid7())

    def new_revision_id(self) -> RevisionId:
        """Return a fresh UUIDv7 to identify a Resource Revision."""
        return RevisionId(self._new_canonical_uuid7())

    def new_relationship_id(self) -> RelationshipId:
        """Return a fresh UUIDv7 to identify a typed Relationship row."""
        return RelationshipId(self._new_canonical_uuid7())

    def new_region_id(self) -> RegionId:
        """Return a fresh UUIDv7 to identify a Content Region."""
        return RegionId(self._new_canonical_uuid7())

    def new_immutable_record_id(self) -> ImmutableRecordId:
        """Return a fresh UUIDv7 to identify an Immutable Record (e.g. Decision)."""
        return ImmutableRecordId(self._new_canonical_uuid7())

    def new_trail_id(self) -> TrailId:
        """Return a fresh UUIDv7 to identify a Trail Resource."""
        return TrailId(self._new_canonical_uuid7())

    def new_trail_revision_id(self) -> TrailRevisionId:
        """Return a fresh UUIDv7 to identify a Trail Revision."""
        return TrailRevisionId(self._new_canonical_uuid7())

    def new_trail_step_id(self) -> TrailStepId:
        """Return a fresh UUIDv7 to identify a Trail Step."""
        return TrailStepId(self._new_canonical_uuid7())

    def new_manifest_id(self) -> ManifestId:
        """Return a fresh UUIDv7 to identify a Provenance Manifest."""
        return ManifestId(self._new_canonical_uuid7())

    # -- validation -----------------------------------------------------------

    def validate_canonical(self, identifier: str) -> bool:
        """Return ``True`` iff *identifier* is a canonical UUIDv7 string.

        ``validate_canonical`` is total over its declared input type. Non
        ``str`` inputs return ``False`` rather than raising so that callers
        validating untrusted payloads (e.g. JSON request bodies) do not need
        an outer ``isinstance`` guard. Uppercase hex digits, missing
        hyphens, wrong group lengths, wrong version nibble, and wrong
        variant bits all yield ``False``.
        """
        if not isinstance(identifier, str):
            return False
        return CANONICAL_UUID7_REGEX.match(identifier) is not None


    # -- conflict detection and binding ---------------------------------------

    def reject_if_duplicate(
        self,
        identifier: str,
        content_digest: str,
        *,
        connection: Optional[Connection] = None,
        kind: Optional[str] = None,
        actor_party_id: Optional[str] = None,
        correlation_id: Optional[str] = None,
        attempted_action: str = "bind.identifier",
        recorded_time: Optional[datetime] = None,
    ) -> None:
        """Register *identifier → content_digest*, raising on conflict.

        Behaviour (per Requirement 1.4 and design §"Error Handling →
        Identifier conflict"):

        1. If *identifier* is not in canonical UUIDv7 form, raise
           :class:`IdentityFormatError`.
        2. If *connection* is omitted, the binding is recorded in the
           in-memory registry. This preserves the task-2.1 surface used
           by unit tests that construct ``IdentityService()`` directly.
        3. If *connection* is supplied, the SQL ``Identifier_Registry``
           table is the source of truth:

           - When the identifier is not yet bound, INSERT a row
             ``(identifier, kind, content_digest, issued_at)`` inside the
             caller's transaction. This is the same transaction as the
             originating write (AD-WS-5), so a caller-side rollback also
             discards the registry row — see the unit-test
             "rollback semantics" case.
           - When the identifier is already bound to *content_digest*,
             return silently. The re-confirmation is idempotent: no new
             row is INSERTed and no audit row is appended.
           - When the identifier is already bound to a different content
             digest, open a separate transaction on
             :attr:`IdentityService.engine`, append a Denial Record with
             ``reason_code='identifier-conflict'``, and raise
             :class:`IdentityConflictError`. The exception propagates so
             the caller's originating transaction rolls back per
             Requirement 2.7 / design §"Error Handling".

        Args:
            identifier: The canonical UUIDv7 string to bind.
            content_digest: Opaque digest string the identifier is being
                bound to. SHA-256 hex strings, manifest hashes, and the
                empty string are all valid — the service does not impose
                a shape on this value.
            connection: Optional SQLAlchemy connection bound to the
                caller's transaction. When provided, the SQL path is
                used; when omitted, the in-memory path is used.
            kind: Required when *connection* is provided. Must be one of
                :data:`ALLOWED_IDENTIFIER_KINDS`. The value is written to
                ``Identifier_Registry.kind`` exactly as supplied.
            actor_party_id: Identity of the Party that owns the
                originating operation. Required for the persistent
                conflict path so that a Denial Record can be appended;
                when omitted the conflict still raises but the audit
                append is skipped (operator-visible logging would take
                over in production).
            correlation_id: Operation correlation identifier shared with
                every audit row written for the same logical operation.
            attempted_action: ``action_type`` written to the denial
                record. Defaults to ``"bind.identifier"``. Callers that
                want their domain action's name attached to the denial
                row (``"create.document_revision"``, etc.) should pass
                it through.
            recorded_time: Optional explicit timestamp for both the
                registry row's ``issued_at`` and the denial record's
                ``recorded_at``. When omitted, :attr:`clock`.now() is
                used; if no clock is wired either, the system UTC clock
                is consulted as a last-resort.

        Raises:
            IdentityFormatError: *identifier* is not canonical UUIDv7.
            IdentityConflictError: *identifier* is already bound to a
                different content digest. On the persistent path a
                Denial Record is appended before this is raised.
            ValueError: *connection* is supplied but *kind* is missing
                or not in :data:`ALLOWED_IDENTIFIER_KINDS`.
            TypeError: *content_digest* is not a ``str``.
        """
        if not self.validate_canonical(identifier):
            raise IdentityFormatError(
                f"identifier {identifier!r} is not in canonical UUIDv7 form "
                f"(expected lowercase 8-4-4-4-12 hex matching "
                f"{CANONICAL_UUID7_REGEX.pattern!r})."
            )
        if not isinstance(content_digest, str):
            raise TypeError(
                f"content_digest must be a str; received {type(content_digest).__name__}"
            )

        if connection is None:
            self._reject_if_duplicate_in_memory(identifier, content_digest)
            return

        if kind is None:
            raise ValueError(
                "kind is required when reject_if_duplicate is called with a "
                f"connection; expected one of {sorted(ALLOWED_IDENTIFIER_KINDS)}."
            )
        if kind not in ALLOWED_IDENTIFIER_KINDS:
            raise ValueError(
                f"unknown identifier kind {kind!r}; "
                f"expected one of {sorted(ALLOWED_IDENTIFIER_KINDS)}."
            )

        self._reject_if_duplicate_sql(
            connection=connection,
            identifier=identifier,
            content_digest=content_digest,
            kind=kind,
            actor_party_id=actor_party_id,
            correlation_id=correlation_id,
            attempted_action=attempted_action,
            recorded_time=recorded_time,
        )

    # -- internal helpers -----------------------------------------------------

    def _reject_if_duplicate_in_memory(
        self, identifier: str, content_digest: str
    ) -> None:
        """In-memory binding path used when no connection is supplied."""
        with self._lock:
            existing = self._registry.get(identifier, _UNBOUND)
            if existing is _UNBOUND:
                self._registry[identifier] = content_digest
                return
            if existing == content_digest:
                # Idempotent re-confirmation of an existing binding.
                return
            raise IdentityConflictError(
                identifier=identifier,
                existing_digest=existing,
                attempted_digest=content_digest,
            )

    def _reject_if_duplicate_sql(
        self,
        *,
        connection: Connection,
        identifier: str,
        content_digest: str,
        kind: str,
        actor_party_id: Optional[str],
        correlation_id: Optional[str],
        attempted_action: str,
        recorded_time: Optional[datetime],
    ) -> None:
        """SQL-backed binding path; conflict appends Denial Record then raises."""
        existing = connection.execute(
            text(
                "SELECT content_digest FROM Identifier_Registry "
                "WHERE identifier = :identifier"
            ),
            {"identifier": identifier},
        ).scalar_one_or_none()

        if existing is None:
            # First binding — INSERT inside the caller's transaction per AD-WS-5.
            issued_at = self._resolve_recorded_at(recorded_time)
            connection.execute(
                text(
                    """
                    INSERT INTO Identifier_Registry
                        (identifier, kind, content_digest, issued_at)
                    VALUES
                        (:identifier, :kind, :content_digest, :issued_at)
                    """
                ),
                {
                    "identifier": identifier,
                    "kind": kind,
                    "content_digest": content_digest,
                    "issued_at": issued_at,
                },
            )
            return

        if existing == content_digest:
            # Idempotent re-confirmation; no INSERT, no audit append.
            return

        # Conflict path — append Denial Record in a separate, audit-only
        # transaction so the row survives the caller-side rollback that
        # follows the exception (design §"Error Handling — Identifier
        # conflict"). Then raise IdentityConflictError so the caller's
        # originating transaction rolls back.
        self._append_identifier_conflict_denial(
            identifier=identifier,
            actor_party_id=actor_party_id,
            correlation_id=correlation_id,
            attempted_action=attempted_action,
            recorded_time=recorded_time,
        )
        raise IdentityConflictError(
            identifier=identifier,
            existing_digest=existing,
            attempted_digest=content_digest,
        )

    def _append_identifier_conflict_denial(
        self,
        *,
        identifier: str,
        actor_party_id: Optional[str],
        correlation_id: Optional[str],
        attempted_action: str,
        recorded_time: Optional[datetime],
    ) -> None:
        """Append the Denial Record for an identifier-conflict, swallowing
        audit failures so the conflict itself is always surfaced.

        The append happens in a *new* transaction on :attr:`engine` so
        that when the caller's originating transaction subsequently rolls
        back the denial row remains persisted (Requirement 13.2). Audit
        append failures are not allowed to mask the conflict — if the
        audit transaction fails, we still raise
        :class:`IdentityConflictError` from
        :meth:`_reject_if_duplicate_sql`. Operator-visible logging of the
        audit failure is delegated to the application composition layer
        (Requirement 7.6).
        """
        if (
            self.engine is None
            or self.audit_log is None
            or actor_party_id is None
            or correlation_id is None
        ):
            # Insufficient wiring to write a denial. The conflict will
            # still be raised by the caller of this helper so that the
            # caller's originating transaction rolls back.
            return
        try:
            with self.engine.begin() as denial_conn:
                self.audit_log.append_denial(
                    denial_conn,
                    actor_party_id=actor_party_id,
                    attempted_action=attempted_action,
                    target_id=identifier,
                    target_revision_id=None,
                    reason_code=IDENTIFIER_CONFLICT_REASON_CODE,
                    correlation_id=correlation_id,
                    recorded_time=recorded_time,
                )
        except (AuditAppendError, SQLAlchemyError):
            # Audit append failed; we deliberately swallow so the
            # conflict is still surfaced to the caller via
            # IdentityConflictError. The application layer is expected
            # to surface ``audit_failure`` to the operator log per
            # Requirement 7.6.
            return

    def _resolve_recorded_at(self, recorded_time: Optional[datetime]) -> str:
        """Resolve the ISO-8601 millisecond timestamp written to the registry.

        Precedence: explicit *recorded_time* wins over :attr:`clock`,
        which wins over the system UTC clock. The system fallback exists
        so an ``IdentityService`` constructed with an engine but no
        clock still works (defensive; production code always wires a
        clock through ``RequestContext``).
        """
        if recorded_time is not None:
            return format_iso8601_ms(recorded_time)
        if self.clock is not None:
            return format_iso8601_ms(self.clock.now())
        return format_iso8601_ms(datetime.now(timezone.utc))

    def _new_canonical_uuid7(self) -> str:
        """Generate one UUIDv7 in canonical lowercase form and record it.

        ``uuid_utils.uuid7()`` returns a UUID object whose ``str()`` form is
        already the canonical lowercase 8-4-4-4-12 hex string. We
        defensively re-validate against :data:`CANONICAL_UUID7_REGEX` so a
        future regression in ``uuid_utils`` cannot silently produce an
        identifier that violates AD-WS-2.

        The new identifier is recorded in the in-memory registry as
        *unbound* so the legacy task-2.1 surface
        (:meth:`reject_if_duplicate` with no connection) continues to
        behave the same way. The SQL backend ignores this in-memory
        record entirely.
        """
        candidate = str(uuid_utils.uuid7())
        if CANONICAL_UUID7_REGEX.match(candidate) is None:
            # This should never happen with a conformant uuid_utils.uuid7();
            # raising :class:`IdentityFormatError` makes the regression
            # immediately visible rather than letting a malformed id leak
            # downstream.
            raise IdentityFormatError(
                f"uuid_utils.uuid7() produced non-canonical identifier {candidate!r}."
            )
        with self._lock:
            # Mark the identifier issued so a later ``reject_if_duplicate``
            # call (in-memory path) sees it. The empty-string sentinel for
            # "issued but not yet bound to a content digest" keeps the
            # in-memory behaviour identical to task 2.1.
            self._registry.setdefault(candidate, _UNBOUND)
        return candidate
